
from __future__ import annotations
from typing import Protocol, List, Optional
from datetime import datetime
from app.domain.models import Conversation, Message

class ConversationStore(Protocol):
    def all(self) -> List[Conversation]: ...
    def find_open_by_customer(self, customer_id: str) -> Optional[Conversation]: ...
    def open(self, conv: Conversation) -> None: ...
    def close(self, conv_id: str, closed_at: datetime) -> None: ...
    def upsert_first_received(self, conv_id: str, when: datetime) -> None: ...
    def upsert_first_response(self, conv_id: str, when: datetime) -> None: ...

class MessageStore(Protocol):
    def all(self) -> List[Message]: ...
    def add(self, msg: Message) -> None: ...
